name: cardchecks-diargram
base: core22
version: '1.0.0'
summary: Card Checks Diagram
description: |
  A new Flutter project.

grade: stable
confinement: strict

parts:
  cardchecks-diargram:
    plugin: flutter
    source: .
    flutter-target: lib/main.dart
    build-packages:
      - clang
      - cmake
      - ninja-build
      - pkg-config
      - libgtk-3-dev
    stage-packages:
      - libgtk-3-0

apps:
  cardchecks-diargram:
    command: cardchecks_diargram
    plugs:
      - network
      - opengl
      - desktop
      - desktop-legacy
    environment:
      # Correctly scale Flutter apps on high-resolution displays.
      GDK_SCALE: '2'
      GDK_DPI_SCALE: '0.5'
